version: 3

vars:
  USERNAME: jmurv
  IMAGE_NAME: seo

tasks:

  app:
    desc: Run app
    cmds:
      - "go run cmd/main.go"

  pb:
    desc: Gen Proto file
    cmds:
      - "protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative api/pb/seo.proto"

  test:
    desc: Run tests
    cmds:
      - "go test ./internal/repo/memory"
      - "go test ./internal/ctrl"
      - "go test ./internal/hdl/http"
      - "go test ./internal/hdl/grpc"

  mocks:
    desc: Generate mocks
    cmds:
      - mockgen -source="./internal/handler/hdl.go" -destination="mocks/mock_ctrl.go" -package=mocks
      - mockgen -source="./internal/controller/ctrl.go" -destination="mocks/mock_repos.go" -package=mocks
      - mockgen -source="./internal/controller/sso/sso.go" -destination="mocks/mock_sso.go" -package=mocks

  build:
    desc: Build app
    cmds:
      - "docker build --no-cache -t {{.USERNAME}}/{{.IMAGE_NAME}}:latest ."

  push:
    desc: Push image to docker registry
    cmds:
      - "docker push {{.USERNAME}}/{{.IMAGE_NAME}}:latest"