// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/hdl.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/hdl.go -destination=mocks/mock_ctrl.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JMURv/seo-svc/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSEOCtrl is a mock of SEOCtrl interface.
type MockSEOCtrl struct {
	ctrl     *gomock.Controller
	recorder *MockSEOCtrlMockRecorder
}

// MockSEOCtrlMockRecorder is the mock recorder for MockSEOCtrl.
type MockSEOCtrlMockRecorder struct {
	mock *MockSEOCtrl
}

// NewMockSEOCtrl creates a new mock instance.
func NewMockSEOCtrl(ctrl *gomock.Controller) *MockSEOCtrl {
	mock := &MockSEOCtrl{ctrl: ctrl}
	mock.recorder = &MockSEOCtrlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSEOCtrl) EXPECT() *MockSEOCtrlMockRecorder {
	return m.recorder
}

// CreateSEO mocks base method.
func (m *MockSEOCtrl) CreateSEO(ctx context.Context, req *model.SEO) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSEO", ctx, req)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSEO indicates an expected call of CreateSEO.
func (mr *MockSEOCtrlMockRecorder) CreateSEO(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSEO", reflect.TypeOf((*MockSEOCtrl)(nil).CreateSEO), ctx, req)
}

// DeleteSEO mocks base method.
func (m *MockSEOCtrl) DeleteSEO(ctx context.Context, name, pk string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSEO", ctx, name, pk)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSEO indicates an expected call of DeleteSEO.
func (mr *MockSEOCtrlMockRecorder) DeleteSEO(ctx, name, pk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSEO", reflect.TypeOf((*MockSEOCtrl)(nil).DeleteSEO), ctx, name, pk)
}

// GetSEO mocks base method.
func (m *MockSEOCtrl) GetSEO(ctx context.Context, name, pk string) (*model.SEO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSEO", ctx, name, pk)
	ret0, _ := ret[0].(*model.SEO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSEO indicates an expected call of GetSEO.
func (mr *MockSEOCtrlMockRecorder) GetSEO(ctx, name, pk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSEO", reflect.TypeOf((*MockSEOCtrl)(nil).GetSEO), ctx, name, pk)
}

// UpdateSEO mocks base method.
func (m *MockSEOCtrl) UpdateSEO(ctx context.Context, req *model.SEO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSEO", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSEO indicates an expected call of UpdateSEO.
func (mr *MockSEOCtrlMockRecorder) UpdateSEO(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSEO", reflect.TypeOf((*MockSEOCtrl)(nil).UpdateSEO), ctx, req)
}
