mode: "dev"
serviceName: "svc-name"

services:
  sso:
    port: 50050
    scheme: "http"
    domain: "localhost"

server:
  port: 8080
  scheme: "http"
  domain: "localhost"

db:
  host: "localhost"
  port: 5432
  user: "app_owner"
  password: "app_password"
  database: "app_db_test"

redis:
  addr: "localhost:6379"
  pass: ""